import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import Providers from '@/components/Providers'
import './globals.css'

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

const inter = Inter({
	subsets: ['latin'],
})

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en'>
			<body
				className={`${inter.className} relative antialiased min-h-screen text-white`}>
				<div
					className='fixed -z-20 bg-cover bg-repeat-y bg-center inset-0'
					style={{
						backgroundImage: "url('/background.jpg')",
					}}></div>

				<Providers>{children}</Providers>
			</body>
		</html>
	)
}
